SET SATURN_ORBIT=C:\SaturnOrbit
SET SS_PROJECT=C:\SS-SonicJump


SET DATA_BUILDED=%SS_PROJECT%\_build
SET DIR_SOUND_INPUT_DATA=%SS_PROJECT%\data\Sound
SET DIR_OUTPUT_DATA=%SS_PROJECT%\CD

SET TOOL_BGCON=%SATURN_ORBIT%\TOOLS\BGCON
SET CMPRUN=%SATURN_ORBIT%\SBL_601\SEGABIN\BIN